# ISSF - Information System on Small Scale Fisheries
# Author: Joshua Murphy
# Date: August 21st, 2018 
# https://github.com/toobigtoignore/issf

# Docker Compose file to orchestrate the containers needed to run ISSF
# as well as a PostgreSQL/PostGIS database

version: '2'

services: 
  web: 
    #image: tbti/web:latest 
    build: "."
    command: "yes" #/bin/bash -c './scripts/wait-for-it.sh 0.0.0.0:5432 -- sleep 30
    #&& python manage.py collectstatic --noinput && gunicorn issf_prod.wsgi -b 0.0.0.0:80'"
    depends_on: 
      - db 
    environment: 
      - DJANGO_SETTINGS_MODULE=issf_prod.settings
    volumes: 
      - "./:/issf:Z"
      - "./static:/static:Z"
    expose:
      - "80"
    stdin_open: true
    tty: true
  db: 
    image: mdillon/postgis:9.5
    ports:
      - "5432:5432"
    volumes: 
      - "./scripts:/scripts:Z"
      - "./data/postgres:/data/postgres/:Z"  
  pgadmin: 
    image: chorss/docker-pgadmin4:2.1 
    ports:
      - "5050:5050"
    volumes: 
      - "./data/pgadmin:/data/pgadmin:Z"
  nginx:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes:
      - "./:/src:Z"
      - "./data/nginx:/etc/nginx/conf.d:Z"
      - "./static:/static:Z"
    depends_on:
      - web 

