# ISSF - Information System on Small Scale Fisheries
# Author: Joshua Murphy
# Date: February 2nd, 2018
# https://github.com/toobigtoignore/issf

# Docker Compose file to orchestrate the containers needed to run ISSF
# as well as a PostgreSQL/PostGIS database

version: '2'

services: 
  issf: 
    build: "."
    command: "/bin/bash -c './scripts/wait-for-it.sh postgres:5432 -- sleep 30
&& python manage.py runserver 0.0.0.0:80'"
    depends_on: 
      - postgres
    environment: 
      - DJANGO_SETTINGS_MODULE=issf_prod.settings
    ports: 
      - "80:80"
    stdin_open: true
    tty: true
    volumes: 
      - "./:/issf:Z"
  postgres: 
    image: mdillon/postgis:9.5
    ports:
      - "5432:5432"
    volumes: 
      - "./scripts:/scripts:Z"
      - "./data/postgres:/data/postgres/:Z"  
  pgadmin: 
    image: chorss/docker-pgadmin4:2.1 
    ports:
      - "5050:5050"
    volumes: 
      - "./data/pgadmin:/data/pgadmin:Z"
